

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            lunrs
tagline:          'neko'
description:      '<a href="https://www.zhihu.com/people/lunrs">zhihu</a>'
url:              http://lunrs.com
baseurl:          /



paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lunrs/lunrs.github.io



encoding: utf-8
plugins: [jekyll-paginate,kramdown,jekyll-gist]